<?php
include "soapconnection.php";

// Turn off all error reporting
error_reporting(0);

//Custom Functions

//Function to Convert stdClass Objects to Multidimensional Arrays
function objectToArray($d) {
		if (is_object($d)) {
			// Gets the properties of the given object
			// with get_object_vars function
			$d = get_object_vars($d);
		}
 
		if (is_array($d)) {
			/*
			* Return array converted to object
			* Using __FUNCTION__ (Magic constant)
			* for recursive call
			*/
			return array_map(__FUNCTION__, $d);
		}
		else {
			// Return array
			return $d;
		}
	}

//Function to search for a value in a multidimentional array and return array index key
function searchForId($id, $array) {
   foreach ($array as $key => $val) {
       if ($val['SkillName'] === $id) {
           return $key;
       }
   }
   return null;
}	
?>
<style type="text/css">
.doSave {
	-moz-box-shadow:inset 0px 1px 1px -50px #ffffff;
	-webkit-box-shadow:inset 0px 1px 1px -50px #ffffff;
	box-shadow:inset 0px 1px 1px -50px #ffffff;
	background:-webkit-gradient( linear, left top, left bottom, color-stop(0.05, #ededed), color-stop(1, #dfdfdf) );
	background:-moz-linear-gradient( center top, #ededed 5%, #dfdfdf 100% );
	filter:progid:DXImageTransform.Microsoft.gradient(startColorstr='#ededed', endColorstr='#dfdfdf');
	background-color:#ededed;
	-moz-border-radius:3px;
	-webkit-border-radius:3px;
	border-radius:3px;
	border:1px solid #8a8a8a;
	display:inline-block;
	color:#2054c4;
	font-family:Verdana;
	font-size:12px;
	font-weight:bold;
	padding:4px 25px;
	text-decoration:none;
	text-shadow:1px 1px 0px #ffffff;
}.doSave:hover {
	background:-webkit-gradient( linear, left top, left bottom, color-stop(0.05, #dfdfdf), color-stop(1, #ededed) );
	background:-moz-linear-gradient( center top, #dfdfdf 5%, #ededed 100% );
	filter:progid:DXImageTransform.Microsoft.gradient(startColorstr='#dfdfdf', endColorstr='#ededed');
	background-color:#dfdfdf;
}.doSave:active {
	position:relative;
	top:1px;
}
/* This imageless css button was generated by CSSButtonGenerator.com */
</style>	
<div style="background: #5f6160; padding: 5px; border-top-right-radius: 5px; border-top-left-radius: 5px; color: #fff; font-family: Arial;">
<b>Report Options</b>
</div>
<div style="background: #fff; padding: 5px; font-family: Arial; border-left: 1px solid #000; border-right: 1px solid #000;">
<form name="theform" id="theform" method="post" action="csg_contact_getrange.php">
Skill Name: <select class="selector_a" id="skillname" name="skillname">
           <option value="All">All</option>
			<?php 
			
			$d = array($client->Skill_GetList($appIDrequest));
            $b = $d[0]->Skill_GetListResult->inSkill;

            $i=-1;
            foreach($b as $skill){ $i++;

            $skill = $d[0]->Skill_GetListResult->inSkill[$i];  

            
           $name = $skill->SkillName;
		   $no = $skill->SkillNo;
		   $pattern = '/^FAST/';          
		   
		   if(preg_match($pattern, $name)){ ?>
		   
		   <option value="<?php echo $name; ?>"><?php echo $name; ?></option>
	   
		   <?php
		   } // if close
		   
		   } // foreach close
		   ?>
			
           </select>

Start: <input name="pickstart" id="pickstart" type="date"/>	
End: <input name="pickend" id="pickend" type="date"/>	
<script src="//ajax.googleapis.com/ajax/libs/jquery/1.7.2/jquery.min.js"></script>

<a id="loading"><input type="submit" value="Submit" class="doSave"></a>
<a class="loading" style="display: none;">
<img src="http://www.insightdomain.net/images/loading_gif.gif" width="75px" height="40px" align="left"/>

</a>
<!-- Script to show/hide Loading div -->
<script>
		$('#loading').click(function() {
        $('.loading').slideToggle("slow");
		document.forms["theform"].submit();
         return false;
});

</script>
</div>
</form>
<div style="background: #ccc; padding: 5px; border-bottom-right-radius: 5px; border-bottom-left-radius: 5px; font-family: Arial;  border-left: 1px solid #000; border-right: 1px solid #000; border-bottom: 1px solid #000;">
</div>

<?php

//Sets Variables based on User Input   
$skill_input = $_POST['skillname'];
if((($_POST['skillname']) == NULL)){

}
else 
if((($_POST['pickstart']) == NULL) || (($_POST['pickend']) == NULL)){
echo "<br><br><b>Please Specify a valid Date Range!</b>";
} 


else {

echo "<br>Search Results for: \"$skill_input\" between " . $_POST['pickstart'] . " and " . $_POST['pickend'] . "<br><br>";
?>
<html>
<head>
		<script type="text/javascript" language="javascript" src="../DataTables-1.9.4/media/js/jquery.dataTables.js"></script>
		<script type="text/javascript" src="../DataTables-1.9.4/extras/ColVis/media/js/ColVis.js"></script>
		<script type="text/javascript" charset="utf-8" src="../DataTables-1.9.4/extras/ColReorder/media/js/ColReorder.js"></script>
		<script type="text/javascript" charset="utf-8" src="../DataTables-1.9.4/media/js/ZeroClipboard.js"></script>
		<script type="text/javascript" charset="utf-8" src="../DataTables-1.9.4/media/js/TableTools.js"></script>
		<script type="text/javascript" src="../DataTables-1.9.4/media/js/jquery.dataTables.editable.js"></script>
		<script src="../DataTables-1.9.4/media/js/jquery.jeditable.js" type="text/javascript"></script>
		<script type="text/javascript" src="../js/date_time.js"></script>

		<script type="text/javascript" charset="utf-8">
			$(document).ready(function() {
				
				oTable = $('#callstable').dataTable({
				    
		            "bJQueryUI": true,
					"sDom": /*'R<"H"TlCfr>t<"F"ip>'*/'<"H"TlCfr>t<"F"ip>',
					/*"oColVis": {"activate": "mouseover"},*/
		            "sPaginationType": "full_numbers",
					"sScrollY": "420px",
					"bPaginate": false,
					"aaSorting": [],
					"bStateSave": false,
					
					
					/*"aoColumnDefs": [
			{ "bVisible": false, "aTargets": [ 1 ] }
		],*/
					"oTableTools": {
					"sSwfPath": "DataTables-1.9.4/media/swf/copy_cvs_xls_pdf.swf",
			"aButtons": ["print"/*,
{
"sExtends": "pdf",
"sButtonText": "Print PDF",
"mColumns": "visible"
},
{
"sExtends": "xls",
"sButtonText": "Export to Spreadsheet",
"mColumns": "all"
}*/
]
		}
					}).makeEditable();
			} );
		</script>	 	

 <style type="text/css" title="currentStyle">
			@import "../DataTables-1.9.4/media/css/demo_table_jui.css";
			@import "../DataTables-1.9.4/examples/examples_support/themes/smoothness/jquery-ui-1.8.4.custom.css";
			@import "../DataTables-1.9.4/extras/ColReorder/media/css/ColReorder.css";
		    @import "../DataTables-1.9.4/extras/ColVis/media/css/ColVis.css";
			@import "../DataTables-1.9.4/media/css/TableTools_JUI.css";
		</style>
	
</head>
<body>		
    
<div class="demo_jui">
   
<table cellspacing="0" cellpadding="0" cellspacing="0" border="0" valign="top" class="display" id="callstable" >
<thead>
<tr style="background: #CAE8EA url(../img/bg_header.jpg) no-repeat;">
<th>Skill</th>
<th>ContactID</th>
<th>Agent No.</th>
<th>From</th>
<th>To</th>
<th>Start Time</th>
<th>Date</th>
<th>Hold Time</th>
<th>Total Dur.</th>
<th>Type</th>

</tr>

</thead>


<tfoot>
<tr>
<th>Skill</th>
<th>ContactID</th>
<th>Agent No.</th>
<th>From</th>
<th>To</th>
<th>Start Time</th>
<th>Date</th>
<th>Hold Time</th>
<th>Total Dur.</th>
<th>Type</th>


</tr>
</tfoot>

<tbody>

		
<?php
//echo "<u>Search Results for: \"$skill_input\"</u><br><br>";
$fail = 0;

//Explode Inputted Start and End Dates
$startdate = $_POST['pickstart'];
$startdate = explode("-", $startdate); 
$enddate = $_POST['pickend'];
$enddate = explode("-", $enddate); 

$time = "00:00:01"; 
$time = explode(":", $time); 

$tz_string = "America/Chicago"; // Use one from list of TZ names http://php.net/manual/en/timezones.php 
$tz_object = new DateTimeZone($tz_string); 

$start = new DateTime();
$start->setTimezone($tz_object);
$start->setDate($startdate[0], $startdate[1], $startdate[2]);
$start->setTime($time[0], $time[1], $time[2]);
$start_f = $start->format('Y-m-d\TH:i:sP');
//echo $start_f;

$end = new DateTime();
$end->setTimezone($tz_object);
$end->setDate($enddate[0], $enddate[1], $enddate[2]);
$end->setTime($time[0], $time[1], $time[2]);
$end_f = $end->format('Y-m-d\TH:i:sP');
//echo $end_f;

/* set parameters and call client */
try {
$parameters = array('applicationId' => $appID, 'startDate' => "$start_f", 'endDate' => "$end_f");
$list = array($client->Contact_GetList($parameters));

$result = $list[0]->Contact_GetListResult->inContact;

//Converts Active List to a searchable multidimentional array
$multi_array = objectToArray($result);


$count=0;

if ( $result != NULL ){
	foreach ($result as $item){
	
	$starttime = $item->StartDate;
	$starttime = explode("T", $starttime);
    $newstarttime = $starttime[1];
    $newstarttime = explode(".", $newstarttime);
	
	$newdate = $item->EndDate;
	$newdate = explode("T", $newdate);
	$datearray = $newdate[0];
	$datearray = explode("-", $datearray);
	$nicedate = $datearray[1] . "/" . $datearray[2] . "/" . $datearray[0];
	
	if(preg_match('/^\d{1}$/',(($item->TotalDurationSeconds)%60))){$seczero = "0";} else {$seczero = "";}
	if(preg_match('/^\d{1}$/',(($item->HoldSeconds)%60))){$seczero1 = "0";} else {$seczero1 = "";}
	
	$from = $item->From;
	$to = $item->To;
	if(strlen($from) == 10){$frommod = "(" . substr($from, 0, 3) . ")" . substr($from, 3, 3) . "-" . substr($from, 6);}else{$frommod = $from;}
	if(strlen($to) == 10){$tomod = "(" . substr($to, 0, 3) . ")" . substr($to, 3, 3) . "-" . substr($to, 6);}else{$tomod = $to;}
	
	if(($item->SkillName)=="$skill_input"){
	    echo "<tr>";
		echo "<th scope='row' class='odd gradeX'>" . $item->SkillName . "</th>";
		echo "<td class='odd gradeX'>" . $item->ContactID . "</td>";
		echo "<td class='odd gradeX'>";
		if($item->AgentNo == 0){echo '?';} else {echo $item->AgentNo;}
		echo "</td>";
		echo "<td class='odd gradeX'>" . $frommod . "</td>";
		echo "<td class='odd gradeX'>" . $tomod . "</td>";
		echo "<td class='odd gradeX'>" . $newstarttime[0] . "</td>";
		echo "<td class='odd gradeX'>" . $nicedate . "</td>";
		echo "<td class='odd gradeX'>";
		if($item->HoldSeconds > 60){echo (substr(((($item->HoldSeconds)/60)), 0, 1)) . ":$seczero1" . (($item->HoldSeconds)%60) . "";} else {echo $item->HoldSeconds . " sec";}
		echo "</td>";
		echo "<td class='odd gradeX'>";
		if($item->TotalDurationSeconds > 60){echo (substr(((($item->TotalDurationSeconds)/60)), 0, 1)) . ":$seczero" . (($item->TotalDurationSeconds)%60) . "";} else {echo $item->TotalDurationSeconds . " sec";}
		echo "</td>";
		echo "<td class='odd gradeX'>";
		if($item->OutboundSkill == false){echo "<img src='http://www.veryicon.com/icon/png/System/Fresh%20Addon/Arrow%20left.png' height='20px' width='20px'/>";} else {echo "<img src='http://aux2.iconpedia.net/uploads/3801716811084014439.png' height='20px' width='20px'/>";}
		echo "</td>";
		echo "</tr>";
		$count++;
	}
	}
	
if ($skill_input == "All"){
        foreach ($result as $item){
		
		$starttime = $item->StartDate;
	    $starttime = explode("T", $starttime);
		$newstarttime = $starttime[1];
		$newstarttime = explode(".", $newstarttime);
		
		$newdate = $item->EndDate;
	    $newdate = explode("T", $newdate);
		$datearray = $newdate[0];
		$datearray = explode("-", $datearray);
		$nicedate = $datearray[1] . "/" . $datearray[2] . "/" . $datearray[0];
		
		if(preg_match('/^\d{1}$/',(($item->TotalDurationSeconds)%60))){$seczero = "0";} else {$seczero = "";}
		if(preg_match('/^\d{1}$/',(($item->HoldSeconds)%60))){$seczero1 = "0";} else {$seczero1 = "";}
		
		$from = $item->From;
		$to = $item->To;
		if(strlen($from) == 10){$frommod = "(" . substr($from, 0, 3) . ")" . substr($from, 3, 3) . "-" . substr($from, 6);}else{$frommod = $from;}
		if(strlen($to) == 10){$tomod = "(" . substr($to, 0, 3) . ")" . substr($to, 3, 3) . "-" . substr($to, 6);}else{$tomod = $to;}
		
		echo "<tr>";
		echo "<th scope='row' class='odd gradeX'>" . $item->SkillName . "</th>";
		echo "<td class='odd gradeX'>" . $item->ContactID . "</td>";
		echo "<td class='odd gradeX'>";
		if($item->AgentNo == 0){echo '?';} else {echo $item->AgentNo;}
		echo "</td>";
		echo "<td class='odd gradeX'>" . $frommod . "</td>";
		echo "<td class='odd gradeX'>" . $tomod . "</td>";
		echo "<td class='odd gradeX'>" . $newstarttime[0] . "</td>";
		echo "<td class='odd gradeX'>" . $nicedate . "</td>";
		echo "<td class='odd gradeX'>";
		if($item->HoldSeconds > 60){echo (substr(((($item->HoldSeconds)/60)), 0, 1)) . ":$seczero1" . (($item->HoldSeconds)%60) . "";} else {echo $item->HoldSeconds . " sec";}
		echo "</td>";
		echo "<td class='odd gradeX'>";
		if($item->TotalDurationSeconds > 60){echo (substr(((($item->TotalDurationSeconds)/60)), 0, 1)) . ":$seczero" . (($item->TotalDurationSeconds)%60) . "";} else {echo $item->TotalDurationSeconds . " sec";}
		echo "</td>";
		echo "<td class='odd gradeX'>";
		if($item->OutboundSkill == false){echo "<img src='http://www.veryicon.com/icon/png/System/Fresh%20Addon/Arrow%20left.png' height='20px' width='20px'/>";} else {echo "<img src='http://aux2.iconpedia.net/uploads/3801716811084014439.png' height='20px' width='20px'/>";}
		echo "</td>";
		echo "</tr>";
		$count++;
    }
	}
	
	
}

?>

</tbody>
</table>
</div>
<?php


//echo "Count: " . $count . " Total Calls";


} catch (Exception $e){
	$fail = 1;
	$error_msg = $error_msg . $e->getMessage() . "</b><br>";
}


}
?>
</body>
</html>